name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    # Leave some time for the post actions to run, particularly cachix to upload
    # any successful builds.
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            channel: nixpkgs-unstable
          - os: macos-latest
            channel: nixpkgs-unstable
    runs-on: ${{ matrix.config.os }}
    concurrency:
      # Different runs of the same job are very likely candidates for (partial)
      # caching, which is defeated in parallel runs. Be nice to GitHub.
      group: ${{ matrix.config.os }}-${{ matrix.config.channel }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: cl-nix-lite
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # This avoids having to fetch an older nixpkgs just for tests and it helps
    # detect problems early.
    # Only bother actually building derivations that are not yet in the
    # store. This prevents nix-build from downloading all built binaries from
    # the store only to discard them immediately afterwards.
    - name: nix flake check
      # Inspired by
      # https://github.com/divnix/std-action/blob/5ead0a37047d44137f950247ee4d3e26fda291d7/run/build-uncached-extractor.sed
      # Works on both BSD (Darwin) and GNU sed. Prints every store path
      # following “.. will be built:”.
      run: |
        set -euo pipefail
        nix build --no-link --dry-run --impure --expr 'let f = builtins.getFlake "git+file://${toString ./.}"; in f.checks.${builtins.currentSystem}' 2>&1 | \
          tee /tmp/nix-build.out | \
          sed -ne '/will be built:$/ {
            # label
            :b
            # next line
            n
            # If the line is indented, it’s a store path
            /^ /{
              # Print it
              p
              # goto label b
              bb
            }
          }' | \
          sed -e 's/$/^*/' | \
          xargs -r nix build --keep-going --print-build-logs --no-link
    - name: Run flake based checks
      run: |
        for example in examples/flakes/* ; do
          (
            cd "$example"
            nix flake check -L \
                --override-input cl-nix-lite "github:${{ github.repository }}/${{ github.sha }}"
          )
        done
    - name: Get all sources
      # Always build full sources, even if already present in the cache, to
      # ensure sources are always refreshed and least likely to be cache evicted
      # by LRU.  They are the most important derivations.
      run: |
        nix build -L --no-link .#sources
    - name: nix-build error output
      if: always()
      run: "cat /tmp/nix-build.out"

  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nobssoftware/nocommit@v3
        name: nocommit
