name: "Nightly ECL"
on:
  workflow_dispatch:
    inputs:
      url:
        description: "git clone URL"
        default: "https://gitlab.com/embeddable-common-lisp/ecl.git"
      ref:
        description: "git reference (e.g. HEAD, refs/heads/mybranch)"
        default: "HEAD"
      # See SBCL workflow note about fetching a revision
  schedule:
    # Run all tests on latest nightly lisp release
    - cron: '12 5 * * *'

jobs:
  ecl:
    timeout-minutes: 300
    # Let’s not waste github’s macos minutes on this
    runs-on: ubuntu-latest
    env:
      LISP_REF: "${{ inputs.ref }}"
      LISP_URL: "${{ inputs.url }}"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: |
            substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
            trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Build all packages against nightly ECL"
        run: |
          nix-build --no-out-link --keep-going \
            ${LISP_URL:+--argstr url "$LISP_URL"} \
            ${LISP_REF:+--argstr ref "$LISP_REF"} \
            examples/channels/all-packages/nightly-ecl.nix
