name: "Nightly"
on:
  workflow_dispatch: {}
  schedule:
    # Run all tests on latest nightly lisp releases
    - cron: '49 3 * * *'

jobs:
  sbcl_master:
    name: "SBCL master"
    timeout-minutes: 300
    # Let’s not waste github’s macos minutes on this
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: |
            substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
            trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Build all packages against latest SBCL master"
        run: |
          nix-build --no-out-link examples/channels/all-packages/nightly-sbcl.nix

  ecl_master:
    name: "ECL master"
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: |
            substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
            trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Build all packages against latest ECL master"
        run: |
          nix-build --no-out-link examples/channels/all-packages/nightly-ecl.nix
