name: "Test"
on:
  pull_request:
  push:
  # Run periodically, to build with latest -unstable releases. Caching makes
  # this a cheap operation when nothing changed, so no need for further logic.
  schedule:
    # 13 is a random non-0 minute to be nice to GitHub because most jobs
    # probably run on the hour
    - cron: '13 */6 * * *'
jobs:
  tests:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            channel: nixpkgs-unstable
          - os: ubuntu-latest
            channel: nixpkgs-23.05
          - os: macos-latest
            channel: nixpkgs-unstable
          - os: macos-latest
            channel: nixpkgs-23.05-darwin
    runs-on: ${{ matrix.config.os }}
    concurrency:
      # Different runs of the same job are very likely candidates for (partial)
      # caching, which is defeated in parallel runs. Be nice to GitHub.
      group: ${{ matrix.config.os }}-${{ matrix.config.channel }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:${{ matrix.config.channel }}
    - uses: cachix/cachix-action@v12
      with:
        name: cl-nix-lite
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - if: runner.os == 'macOS'
      name: Install GNU sed
      # BSD sed has a weird interpretation of -e 0,/.../
      run: "nix-env -f '<nixpkgs>' -iA gnused"
    - name: Update flake locks to use this cl-nix-lite
      run: "cd examples/flake-app && nix flake lock --override-input cl-nix-lite ../.."
    # Only bother actually building derivations that are not yet in the
    # store. This prevents nix-build from downloading all built binaries from
    # the store only to discard them immediately afterwards.
    - name: All examples
      run: |
        cd examples && \
          nix-build --no-out-link --dry-run 2>&1 | \
          sed -e '0,/will be built:$/d' -e '/^[^ ]/,$d' | \
          xargs -r nix-build --no-out-link
