name: "Test"
on:
  pull_request:
  push:
  # Run periodically, to build with latest -unstable releases. Caching makes
  # this a cheap operation when nothing changed, so no need for further logic.
  schedule:
    # 13 is a random non-0 minute to be nice to GitHub because most jobs
    # probably run on the hour
    - cron: '13 */6 * * *'
jobs:
  tests:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            channel: nixpkgs-unstable
          - os: ubuntu-latest
            channel: nixos-23.05
          - os: macos-latest
            channel: nixpkgs-unstable
          - os: macos-latest
            channel: nixpkgs-23.05-darwin
    runs-on: ${{ matrix.config.os }}
    concurrency:
      # Different runs of the same job are very likely candidates for (partial)
      # caching, which is defeated in parallel runs. Be nice to GitHub.
      group: ${{ matrix.config.os }}-${{ matrix.config.channel }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Configure Cachix
      uses: cachix/cachix-action@v12
      with:
        name: cl-nix-lite
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Pin nixpkgs to ${{ matrix.config.channel }}
      run: "nix registry pin nixpkgs github:NixOS/nixpkgs/${{ matrix.config.channel }}"
    - name: Update flake locks to use this cl-nix-lite
      run: "cd examples/flake-app && nix flake lock --override-input cl-nix-lite ../.."
    - name: All examples
      run: "cd examples && nix-build --no-out-link"
